config/routes.rb
Rails.application.routes.draw do
  root 'games#new'

  resource :game do
    post :throw
  end
end

app/models/game.rb
class Game
  SIGNS = %w[Rock Paper Scissors]

  attr_reader :sign, :throw_result

  def initialize(sign)
    @sign = sign
  end

  def throw
    @throw_result = SIGNS.sample
  end

  def result
    case sign
    when 'Rock'
      case throw_result
      when 'Rock'
        'Draw'
      when 'Paper'
        'Lose'
      when 'Scissors'
        'Win'
      end
    when 'Paper'
      case throw_result
      when 'Rock'
        'Win'
      when 'Paper'
        'Draw'
      when 'Scissors'
        'Lose'
      end
    when 'Scissors'
      case throw_result
      when 'Rock'
        'Lose'
      when 'Paper'
        'Win'
      when 'Scissors'
        'Draw'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new

  end

  def throw
    @game = Game.new(params[:sign])
    @game.throw
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/new.html.erb
<div class="container">

    <br class="">
    <br class="">
    <br class="">
    <br class="">
    <div class="row-fluid">
        <div class="span5 offsetHalf block">
            <div class="pull-center">
                 <h1 class="">YOU</h1>
CHOOSE WISELY.
                <br class="">
                 <h1 class=""><i class="icon-male icon-4x"></i></h1>
                 <%= form_tag throw_game_path, method: :post, id: 'new_game' do %>
  Choose
  <%= select_tag :sign, options_for_select(Game::SIGNS) %>
and
  <div class="btn-group">

  <button type="submit" class="btn btn-success">Throw</button>
  </div>
  <!--
  <button type="submit" class="btn btn-primary btn-flat">THROW<i class="pull-right icon-chevron-right icon-large"></i>
                </button>
-->

<% end %>


            </div>
        </div>
        <div class="span5 block">
            <div class="pull-center">
                  <h1 class="">SERVER</h1>
RANDOM THROW.
                <br class="">
                  <h1 class=""><i class="icon-fire icon-4x"></i></h1>


            </div>
        </div>
    </div>
    <br class="">
    <br class="">
    <br class="">


  <!-- script references -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>

app/views/games/throw.html.erb
<div class="container">


    <br class="">
    <h3>You <%= @game.result %>!
<div class="btn-group">
  <%= link_to 'New Game', new_game_path, class: 'btn btn-success' %>
  </div>
  </h3>

    <br class="">
    <div class="row-fluid">
        <div class="span5 offsetHalf block">
            <div class="pull-center">
                 <h1 class="">YOU</h1>
CHOOSE WISELY.
                <br class="">
                 <div><%= image_tag "#{@game.sign.downcase}.jpg" %></div>
                <div><%= @game.sign %></div>

            </div>
        </div>
        <div class="span5 block">
            <div class="pull-center">
                  <h1 class="">SERVER</h1>
RANDOM THROW.
                <br class="">
                  <div><%= image_tag "#{@game.throw_result.downcase}.jpg"%></div>
                  <div><%= @game.throw_result %></div>


            </div>
        </div>
    </div>
    <br class="">
    <br class="">
    <br class="">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockPaperScissors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<style type="text/css">
@import url('http://fonts.googleapis.com/css?family=Open+Sans:200,300');

body { 
  background: url("green_suburb.jpg") no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  color:#fff;
    background-color:#333;
    font-family: 'Open Sans',Arial,Helvetica,Sans-Serif;
}

a:link, a:visited {
  color:#eee;
}

.pull-center{
   text-align: center;
}

.block {
  background-color:rgba(0,0,0,0.2);
    height:370px;
    padding-left:12px;
    padding-right:12px;
}

.block-sm {
    height:180px;
}

.btn-flat {
    font-family: 'Open Sans',Arial,Helvetica,Sans-Serif;
  border-radius:0px;
    border-width:0;
    background-image:none;
    padding:16px;
    margin:0 auto;
    margin-top:15px;
    width:70%;
    font-size:20pt;
}

/* mini carousel */
.carousel-inner img {
  width:100%;
    height:100%;
}

#myCarousel {
  font-size:90%;
}

.carousel-controls-mini {
  margin-left:42%;
}

.carousel-controls-mini > a {
  border:1px solid #eee;
    margin:1px;
    width:20px;
    display:block;
    float:left;
    text-align:center;
}

#carousel-bounding-box {
  margin:0 auto;
  width:300px;
}

</style>

</head>
<body>

  <div class="container">
   <br class="">

    <br class="">
    <br class="">
    <div class="row-fluid">
         <h1><strong>ROCK PAPER SCISSORS GAME - June 28 2017</strong></h1>

        <p>By Damien Le</p>
    </div>
 <div class="container">
      <%= yield %>

  </div>

</body>
</html>